[build]
command = "pnpm run build"
publish = "apps/client-web-spa/build/client"

[dev]
command = "pnpm run dev"
targetPort = 5173

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
